name: interview_mobile_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Local storage
  shared_preferences: ^2.0.5

  # Localization
  # Fix from ^0.17.1
  intl: ^0.18.1
  intl_utils: ^2.8.6

  # Functional programing thingies
  dartz: ^0.10.0
  rxdart: ^0.27.2

  # Service locator
  get_it: ^7.2.0
  provider: ^6.0.1

  # Value equality
  equatable: ^2.0.3

  # Managing configurations
  global_configuration: ^2.0.0-nullsafety.1

  # network
  internet_connection_checker_plus: ^2.1.0
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^5.0.2
  dio: ^5.4.0

  # svg image
  flutter_svg: ^2.0.9

  #cached image
  cached_network_image: ^3.3.0

  #font awesome flutter
  font_awesome_flutter: ^10.6.0

  carousel_slider: ^4.2.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:

  flutter_lints: ^2.0.0

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  # Optional
  integrations:
    flutter_svg: true
    rive: true
  assets:
    enabled: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/cfg/
    - assets/fonts/
    - assets/images/png/
    - assets/images/svg/
    - assets/images/jpg/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Inter
       fonts:
         - asset: assets/fonts/Inter-Medium.ttf
         - asset: assets/fonts/Inter-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true